# Generated by Django 3.1.1 on 2020-09-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actormodel',
            old_name='actorid',
            new_name='actorID',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movieid',
            new_name='movieID',
        ),
    ]
