# Generated by Django 3.1.1 on 2020-09-12 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0003_auto_20200912_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actorID', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
                ('hometown', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movieID', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
                ('actors', models.ManyToManyField(to='mysiteapp.ActorModel')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysiteapp.moviemodel'),
        ),
    ]
