# Generated by Django 3.1.1 on 2020-09-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysiteapp', '0004_auto_20200912_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actormodel',
            name='actorID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actormodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='movieID',
            field=models.IntegerField(default=0),
        ),
    ]
